on:
  push:
    branches:
      - main
      - dev
      - staging
    tags:
      - v*

name: Generalized Reproducible Deployments
jobs:
  push:
    name: Invoke General Reproducible Docker Build Pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@8c3f20df09ac63af7b3ae3d7c91f105f857d8497 # v4.0.0
      with:
        aws-access-key-id: ${{ secrets.GDBP_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.GDBP_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Override GITHUB_REF and thus ECR destination for main
      run: echo "GITHUB_REF_OVERRIDE=refs/heads/dev" >> $GITHUB_ENV
      if: ${{ github.ref == 'refs/heads/main' }}
    - name: Set REPRODUCIBLE to get a reproducible build
      run: echo "REPRODUCIBLE=true" >> $GITHUB_ENV
    - name: Generalized Deployments
      uses: brave-intl/general-docker-build-pipeline-action@a5abec689bc65b6a985ed8527d741a130c1483af # v1.0.11
