on:
  push:
    branches:
      - main
      - dev
      - staging
    tags:
      - v*

name: Generalized Reproducible Deployments
jobs:
  push:
    name: Invoke General Reproducible Docker Build Pipeline
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
      with:
        role-to-assume: ${{ secrets.GDBP_AWS_IAM_ROLE_ARN }}
        aws-region: us-west-2
    - name: Override GITHUB_REF and thus ECR destination for main
      run: echo "GITHUB_REF_OVERRIDE=refs/heads/dev" >> $GITHUB_ENV
      if: ${{ github.ref == 'refs/heads/main' }}
    - name: Set REPRODUCIBLE to get a reproducible build
      run: echo "REPRODUCIBLE=true" >> $GITHUB_ENV
    - name: Generalized Deployments
      uses: brave-intl/general-docker-build-pipeline-action@535977191a2f69ade89e2140f8e554ec4573ac24 # v1.0.12
