name: Makefile

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
     - main

env:
  CARGO_TERM_COLOR: always

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Build
      run: make
