name: Makefile

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
     - main

env:
  CARGO_TERM_COLOR: always

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

    - name: Build
      run: make
