name: Makefile

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
     - main

env:
  CARGO_TERM_COLOR: always

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

    - name: Build
      run: make
